# Generated by Django 6.0.7 on 2026-08-07 09:14

from django.db import migrations
class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bible',
            old_name='Chapters',
            new_name='Chapter',
        ),
    ]
