# Generated by Django 6.0.7 on 2026-08-12 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_rename_chapters_bible_chapter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Rating', models.DecimalField(decimal_places=2, max_digits=10)),
                ('Description', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='Bible',
        ),
    ]
