# Generated by Django 6.0.7 on 2026-09-07 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='Join_date',
            field=models.DateField(auto_now=True),
        ),
    ]
