# Generated by Django 6.0.7 on 2026-09-07 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0002_person_join_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='Join_date',
            new_name='Date_created',
        ),
    ]
